namespace CrabDesk.Core;

public sealed record BuiltInOrganizationRuleDefinition(
    string Id,
    string Title,
    int Priority,
    IReadOnlyList<DesktopItemKind> ItemKinds,
    IReadOnlyList<string> Extensions,
    bool IsFallback = false);

public static class BuiltInOrganizationRules
{
    public const string DirectoryId = "directory";
    public const string DocumentsId = "documents";
    public const string ImagesId = "images";
    public const string ArchivesId = "archives";
    public const string OtherId = "other";

    public static IReadOnlyList<BuiltInOrganizationRuleDefinition> Definitions { get; } =
    [
        new(DirectoryId, "目录", 10, [DesktopItemKind.Folder], []),
        new(DocumentsId, "文档", 20, [DesktopItemKind.File],
            [".doc", ".docx", ".pdf", ".ppt", ".pptx", ".xls", ".xlsx", ".txt", ".md", ".rtf"]),
        new(ImagesId, "图片", 30, [DesktopItemKind.File],
            [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".webp", ".tif", ".tiff", ".svg", ".ico"]),
        new(ArchivesId, "压缩", 40, [DesktopItemKind.File],
            [".zip", ".rar", ".7z", ".tar", ".gz", ".bz2", ".xz"]),
        new(OtherId, "其它", 50,
            [DesktopItemKind.File, DesktopItemKind.Folder, DesktopItemKind.Shortcut, DesktopItemKind.Shell],
            [],
            true)
    ];

    public static List<OrganizationRule> CreateDefaults() =>
        Definitions.Select(CreateRule).ToList();

    public static void EnsureRules(CrabDeskState state, bool adoptLegacyDefaults = false)
    {
        state.OrganizationRules ??= [];
        var nextPriority = state.OrganizationRules.Count == 0
            ? 10
            : state.OrganizationRules.Max(rule => rule.Priority) + 10;

        foreach (var definition in Definitions)
        {
            var rule = state.OrganizationRules.FirstOrDefault(candidate =>
                string.Equals(candidate.BuiltInId, definition.Id, StringComparison.OrdinalIgnoreCase));
            if (rule is null && adoptLegacyDefaults)
            {
                rule = state.OrganizationRules.FirstOrDefault(candidate =>
                    IsLegacyDefault(state, candidate, definition));
                if (rule is not null)
                {
                    ApplyDefinition(rule, definition);
                }
            }

            if (rule is not null)
            {
                continue;
            }

            rule = CreateRule(definition);
            rule.Priority = nextPriority;
            nextPriority += 10;
            state.OrganizationRules.Add(rule);
        }
    }

    public static bool IsFallback(OrganizationRule rule) =>
        string.Equals(rule.BuiltInId, OtherId, StringComparison.OrdinalIgnoreCase);

    private static OrganizationRule CreateRule(BuiltInOrganizationRuleDefinition definition) => new()
    {
        BuiltInId = definition.Id,
        Title = definition.Title,
        Enabled = true,
        Priority = definition.Priority,
        ItemKinds = definition.ItemKinds.ToList(),
        NamePattern = "*",
        Extensions = definition.Extensions.ToList(),
        Action = OrganizationRuleAction.AssignToBox
    };

    private static void ApplyDefinition(
        OrganizationRule rule,
        BuiltInOrganizationRuleDefinition definition)
    {
        rule.BuiltInId = definition.Id;
        rule.Title = definition.Title;
        rule.Priority = definition.Priority;
        rule.ItemKinds = definition.ItemKinds.ToList();
        rule.NamePattern = "*";
        rule.Extensions = definition.Extensions.ToList();
        rule.Action = OrganizationRuleAction.AssignToBox;
    }

    private static bool IsLegacyDefault(
        CrabDeskState state,
        OrganizationRule rule,
        BuiltInOrganizationRuleDefinition definition)
    {
        if (!string.IsNullOrWhiteSpace(rule.BuiltInId) ||
            rule.TargetBoxId is not { } targetBoxId ||
            rule.Action != OrganizationRuleAction.AssignToBox ||
            !string.Equals(rule.NamePattern, "*", StringComparison.Ordinal))
        {
            return false;
        }

        var box = state.Boxes.FirstOrDefault(candidate =>
            candidate.Id == targetBoxId && candidate.IsAutoGenerated);
        if (box is null)
        {
            return false;
        }

        return definition.Id switch
        {
            DirectoryId => MatchesLegacyShape(rule, "目录", [DesktopItemKind.Folder], []),
            DocumentsId => MatchesLegacyShape(rule, "文档", [DesktopItemKind.File],
                ["doc", "docx", "pdf", "rtf", "txt", "xls", "xlsx", "ppt", "pptx", "md"]),
            ImagesId => MatchesLegacyShape(rule, "图片", [DesktopItemKind.File],
                ["bmp", "gif", "jpg", "jpeg", "png", "tif", "tiff", "webp", "heic"]),
            ArchivesId => MatchesLegacyShape(rule, "压缩包", [DesktopItemKind.File],
                ["7z", "bz2", "gz", "rar", "tar", "xz", "zip"]),
            _ => false
        };
    }

    private static bool MatchesLegacyShape(
        OrganizationRule rule,
        string title,
        IReadOnlyCollection<DesktopItemKind> kinds,
        IReadOnlyCollection<string> extensions)
    {
        if (!string.Equals(rule.Title, title, StringComparison.CurrentCultureIgnoreCase) ||
            !rule.ItemKinds.ToHashSet().SetEquals(kinds))
        {
            return false;
        }

        var normalized = rule.Extensions
            .Select(extension => extension.Trim().TrimStart('.'))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
        return normalized.SetEquals(extensions);
    }
}
