using System.Text.Json.Serialization;

namespace CrabDesk.Core;

public enum DesktopItemKind
{
    File,
    Folder,
    Shortcut,
    Shell
}

public enum BoxViewMode
{
    Grid,
    List
}

public enum BoxSortMode
{
    Manual,
    Name,
    Type,
    Modified
}

public enum BoxTransferEffect
{
    None,
    VirtualMove,
    CopyFiles,
    MoveFiles
}

public enum BoxTitleAlignment
{
    Left,
    Center
}

public enum ApplicationThemeMode
{
    System,
    Light,
    Dark
}

public enum OrganizationRuleAction
{
    AssignToBox,
    KeepUnassigned,
    Ignore
}

public enum MappedFolderAvailability
{
    Available,
    Missing,
    Offline,
    AccessDenied,
    Error
}

public enum MappedFolderItemCategory
{
    All,
    Folder,
    Image,
    Document,
    Archive,
    Other
}

[Flags]
public enum HotkeyModifiers
{
    None = 0,
    Alt = 1,
    Control = 2,
    Shift = 4,
    Windows = 8
}

public enum HotkeyKey
{
    A = 0x41, B, C, D, E, F, G, H, I, J, K, L, M,
    N, O, P, Q, R, S, T, U, V, W, X, Y, Z,
    F1 = 0x70, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12
}

public enum HotkeyAction
{
    ShowDesktop,
    OrganizeDesktop
}

public enum HotkeyRegistrationStatus
{
    Disabled,
    Registered,
    Conflict,
    Failed
}

public enum UpdateChannel
{
    Stable,
    Preview
}

public enum UpdateCheckStatus
{
    NotChecked,
    NotConfigured,
    UpToDate,
    UpdateAvailable,
    Offline,
    RateLimited,
    Failed
}

public readonly record struct LayoutRect(double X, double Y, double Width, double Height)
{
    public LayoutRect Clamp(LayoutRect bounds, double minWidth = 180, double minHeight = 120)
    {
        var width = Math.Clamp(Width, minWidth, Math.Max(minWidth, bounds.Width));
        var height = Math.Clamp(Height, minHeight, Math.Max(minHeight, bounds.Height));
        var x = Math.Clamp(X, bounds.X, bounds.X + bounds.Width - width);
        var y = Math.Clamp(Y, bounds.Y, bounds.Y + bounds.Height - height);
        return new LayoutRect(x, y, width, height);
    }

    public bool Contains(double x, double y) =>
        x >= X && x <= X + Width && y >= Y && y <= Y + Height;

    public bool Intersects(LayoutRect other) =>
        Width > 0 && Height > 0 && other.Width > 0 && other.Height > 0 &&
        X < other.X + other.Width && X + Width > other.X &&
        Y < other.Y + other.Height && Y + Height > other.Y;
}

public sealed class BoxAppearance
{
    public string Background { get; set; } = "#FF2A2D32";
    public string Accent { get; set; } = "#FF4EA1D3";
    public double Opacity { get; set; } = 1;
    public double IconSize { get; set; } = 42;
    public string LabelFontFamily { get; set; } = "Segoe UI";
    public double LabelFontSize { get; set; } = 8.5;
    public bool ShowItemLabels { get; set; } = true;
    public double TitleBarHeight { get; set; } = 38;
    public BoxTitleAlignment TitleAlignment { get; set; } = BoxTitleAlignment.Left;
    public string TitleColor { get; set; } = "Auto";
    public string TitleFontFamily { get; set; } = "Segoe UI";
    public double TitleFontSize { get; set; } = 10;
    public bool TitleFontBold { get; set; } = true;
}

public sealed class DesktopBox
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string Title { get; set; } = "新盒子";
    public string MonitorId { get; set; } = string.Empty;
    // Persistent back-to-front order within one monitor. Native window order
    // remains owned by the desktop surface, never by individual boxes.
    public int StackOrder { get; set; }
    public LayoutRect Bounds { get; set; } = new(32, 32, 420, 300);
    // Kept in the JSON shape for backward compatibility. It is always derived
    // from ExpandOnHover, so the box has only two display modes.
    public bool IsCollapsed { get; set; }
    // False: fixed expanded. True: collapsed until its title bar is hovered.
    public bool ExpandOnHover { get; set; }
    public bool IsSystemBox { get; set; }
    public bool IsAutoGenerated { get; set; }
    public BoxViewMode ViewMode { get; set; } = BoxViewMode.Grid;
    public BoxSortMode SortMode { get; set; } = BoxSortMode.Name;
    public BoxAppearance Appearance { get; set; } = new();
    public List<string> ItemOrder { get; set; } = [];
    // Normal boxes can group their assigned desktop items into user-created
    // tabs. Mapped folders continue to use their file-type tabs instead.
    public List<DesktopBoxTab> ManualTabs { get; set; } = [];
    public Dictionary<string, Guid> ItemTabAssignments { get; set; } =
        new(StringComparer.OrdinalIgnoreCase);
    public MappedFolderSettings? MappedFolder { get; set; }

    [JsonIgnore]
    public bool IsMappedFolder => MappedFolder is not null;
}

public sealed class DesktopBoxTab
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string Title { get; set; } = "新标签";
}

public sealed class MappedFolderSettings
{
    public string Path { get; set; } = string.Empty;
    public bool IsReadOnly { get; set; }
    public bool EnableCategoryTabs { get; set; } = true;
}

public sealed record MappedFolderSnapshot(
    string Path,
    MappedFolderAvailability Availability,
    IReadOnlyList<DesktopItemRef> Items,
    string? Message = null)
{
    public bool IsAvailable => Availability == MappedFolderAvailability.Available;
}

public readonly record struct DesktopItemKey(string Kind, string Value)
{
    public override string ToString() => $"{Kind}:{Value}";

    public static DesktopItemKey Parse(string value)
    {
        var separator = value.IndexOf(':');
        return separator < 0
            ? new DesktopItemKey("path", value)
            : new DesktopItemKey(value[..separator], value[(separator + 1)..]);
    }
}

public sealed class DesktopItemRef
{
    public required DesktopItemKey Key { get; init; }
    public required string DisplayName { get; init; }
    public required string ParsingName { get; init; }
    public string? FileSystemPath { get; init; }
    public DesktopItemKind Kind { get; init; }
    public DateTimeOffset? ModifiedAt { get; init; }
    public bool IsReadOnly { get; init; }
    public bool IsSystem => Kind == DesktopItemKind.Shell;
}

/// <summary>
/// A user-chosen desktop grid slot. Positions are stored as grid coordinates
/// rather than pixels so they remain stable when Explorer's icon scale or
/// monitor DPI changes.
/// </summary>
public sealed class DesktopIconPlacement
{
    public string MonitorId { get; set; } = string.Empty;
    public int Column { get; set; }
    public int Row { get; set; }
}

/// <summary>
/// Captures the grid arrangement produced by the most recent Explorer sort.
/// The snapshot is intentionally retained after a manual drag, matching the
/// native desktop behavior where a sort is a one-time arrangement rather than
/// a continuously enforced ordering.
/// </summary>
public sealed class DesktopIconLayoutSnapshot
{
    public string MonitorId { get; set; } = string.Empty;
    public int Column { get; set; }
    public int Row { get; set; }
}

public sealed class MonitorLayout
{
    public required string Id { get; init; }
    public required string DeviceName { get; init; }
    public required LayoutRect Bounds { get; init; }
    public required LayoutRect WorkArea { get; init; }
    public required LayoutRect PixelBounds { get; init; }
    public required LayoutRect PixelWorkArea { get; init; }
    public double DpiScale { get; init; } = 1;
    public bool IsPrimary { get; init; }
}

public sealed record DesktopHostDiagnostics(
    DateTimeOffset CapturedAt,
    bool Connected,
    bool Paused,
    string DesktopParentHandle,
    string DesktopParentClass,
    string DesktopViewHandle,
    string DesktopViewClass,
    string DesktopListViewHandle,
    int MonitorCount,
    int SurfaceCount,
    int BoxCount,
    int MappedBoxCount,
    int AssignmentCount,
    int SchemaVersion,
    string Theme,
    IReadOnlyList<string> Monitors);

public sealed record LayoutResetResult(LayoutBackupInfo Backup, int DisabledRuleCount);

public sealed record AiClassificationAssignment(string ItemKey, string ItemName, string Label);

public sealed record AiClassificationApplyResult(
    int Requested,
    int Classified,
    int Applied,
    int CreatedBoxes,
    int Unmatched,
    IReadOnlyList<AiClassificationAssignment> Assignments);

public sealed record FileClipboardContent(IReadOnlyList<string> Paths, bool Move)
{
    public bool HasFiles => Paths.Count > 0;
}

public sealed record FileImportItemResult(
    string SourcePath,
    string? DestinationPath,
    string? ErrorMessage)
{
    public bool Succeeded => DestinationPath is not null && string.IsNullOrWhiteSpace(ErrorMessage);
}

public sealed record FileImportBatchResult(IReadOnlyList<FileImportItemResult> Items)
{
    public static FileImportBatchResult Empty { get; } = new([]);

    public IReadOnlyList<FileImportItemResult> SuccessfulItems => Items
        .Where(item => item.Succeeded)
        .ToArray();

    public IReadOnlyList<FileImportItemResult> FailedItems => Items
        .Where(item => !item.Succeeded)
        .ToArray();

    public IReadOnlyList<string> ImportedPaths => SuccessfulItems
        .Select(item => item.DestinationPath!)
        .ToArray();

    public int SucceededCount => Items.Count(item => item.Succeeded);
    public int FailedCount => Items.Count - SucceededCount;
    public bool HasFailures => FailedCount > 0;
}

public sealed record BoxPasteResult(int AssignedCount, FileImportBatchResult ImportResult)
{
    public int FailedCount => ImportResult.FailedCount;
    public bool HasFailures => ImportResult.HasFailures;
}

public sealed class AppSettings
{
    public bool StartWithWindows { get; set; }
    public bool TakeOverDesktop { get; set; }
    public bool ShowSystemItems { get; set; } = true;
    // When false (default) the replacement desktop hides Office ~$ lock files
    // and files with Hidden/System attributes, matching Explorer.
    public bool ShowHiddenFiles { get; set; }
    public bool ConfirmDeleteBox { get; set; } = true;
    public ApplicationThemeMode ThemeMode { get; set; } = ApplicationThemeMode.System;
    public string WindowBackdrop { get; set; } = "Mica";
    public DesktopBehaviorSettings DesktopBehavior { get; set; } = new();
    public GlobalAppearanceSettings Appearance { get; set; } = new();
    public BackupSettings Backup { get; set; } = new();
    public AiClassificationSettings AiClassification { get; set; } = new();
    public HotkeySettings Hotkeys { get; set; } = new();
    public UpdateSettings Updates { get; set; } = new();
    public string Language { get; set; } = "zh-CN";
}

public sealed class AiClassificationSettings
{
    public string BaseUrl { get; set; } = string.Empty;
    [JsonIgnore]
    public string ApiKey { get; set; } = string.Empty;
    public string Model { get; set; } = string.Empty;
    public string CategoryLabels { get; set; } = string.Empty;
    public string CustomPrompt { get; set; } =
        "请仅根据桌面图标的名称判断用途，并将每个图标归入最合适的分类标签。";
    public bool ReassignExistingItems { get; set; }
}

public sealed class UpdateSettings
{
    public bool CheckOnStartup { get; set; } = true;
    public UpdateChannel Channel { get; set; } = UpdateChannel.Stable;
    public DateTimeOffset? LastCheckedAt { get; set; }
    public UpdateCheckStatus LastStatus { get; set; } = UpdateCheckStatus.NotChecked;
    public string LastMessage { get; set; } = string.Empty;
    public string CachedETag { get; set; } = string.Empty;
    public string LatestKnownVersion { get; set; } = string.Empty;
    public string CachedReleaseName { get; set; } = string.Empty;
    public DateTimeOffset? CachedPublishedAt { get; set; }
    public string CachedReleaseNotes { get; set; } = string.Empty;
    public string CachedReleasePageUrl { get; set; } = string.Empty;
    public string CachedInstallerUrl { get; set; } = string.Empty;
    public string CachedSha256Url { get; set; } = string.Empty;
    public bool CachedIsPrerelease { get; set; }
    public string RepositoryOwner { get; set; } = string.Empty;
    public string RepositoryName { get; set; } = string.Empty;
}

public sealed record UpdateCheckRequest(
    string RepositoryOwner,
    string RepositoryName,
    string CurrentVersion,
    UpdateChannel Channel,
    string CachedETag,
    string CachedLatestVersion,
    string CachedReleaseName,
    DateTimeOffset? CachedPublishedAt,
    string CachedReleaseNotes,
    string CachedReleasePageUrl,
    string CachedInstallerUrl,
    string CachedSha256Url,
    bool CachedIsPrerelease,
    string InstallerAssetName = "CrabDesk-Setup-x64.exe");

public sealed record UpdateCheckResult(
    UpdateCheckStatus Status,
    string CurrentVersion,
    string LatestVersion = "",
    string ReleaseName = "",
    DateTimeOffset? PublishedAt = null,
    string ReleaseNotes = "",
    string ReleasePageUrl = "",
    string InstallerUrl = "",
    string Sha256Url = "",
    bool IsPrerelease = false,
    string ETag = "",
    string Message = "",
    string InstallerAssetName = "CrabDesk-Setup-x64.exe");

public sealed record UpdateDownloadRequest(
    string InstallerUrl,
    string Sha256Url,
    string Version,
    string DestinationDirectory,
    string InstallerAssetName = "CrabDesk-Setup-x64.exe");

public sealed record UpdateDownloadProgress(
    string Stage,
    long BytesReceived = 0,
    long? TotalBytes = null)
{
    public double Percentage => TotalBytes is > 0
        ? Math.Clamp(BytesReceived * 100d / TotalBytes.Value, 0, 100)
        : 0;
}

public sealed record UpdateDownloadResult(
    bool Success,
    string InstallerPath = "",
    string Sha256 = "",
    bool SignatureTrusted = false,
    string SignerSubject = "",
    bool IsPrerelease = false,
    string Message = "");

public sealed class HotkeySettings
{
    public HotkeyBinding ShowDesktop { get; set; } = new()
    {
        Modifiers = HotkeyModifiers.Control | HotkeyModifiers.Alt,
        Key = HotkeyKey.D
    };
    public HotkeyBinding OrganizeDesktop { get; set; } = new()
    {
        Modifiers = HotkeyModifiers.Control | HotkeyModifiers.Alt,
        Key = HotkeyKey.O
    };
}

public sealed class HotkeyBinding
{
    public bool Enabled { get; set; }
    public HotkeyModifiers Modifiers { get; set; }
    public HotkeyKey Key { get; set; }
}

public sealed class GlobalHotkeyPressedEventArgs(HotkeyAction action) : EventArgs
{
    public HotkeyAction Action { get; } = action;
}

public sealed class DesktopBehaviorSettings
{
    public bool LaunchToTray { get; set; }
    public bool RefreshAfterRename { get; set; } = true;
    public bool ExpandBoxOnHover { get; set; }
}

public sealed class GlobalAppearanceSettings
{
    public double CornerRadius { get; set; } = 8;
    public bool ShowBorder { get; set; } = true;
    public bool ShowResizeGrip { get; set; } = true;
    public double IconHorizontalSpacing { get; set; } = 76;
    public double IconVerticalSpacing { get; set; } = 80;
    public string SelectionColor { get; set; } = "#FF4A5BB1";
    public bool HoverFeedback { get; set; } = true;
    public bool AnimationEnabled { get; set; } = true;
    // Empty family/zero size keeps the system icon-title font; set both to
    // override the desktop item label appearance.
    public string IconLabelFontFamily { get; set; } = string.Empty;
    public double IconLabelFontSize { get; set; }
}

public sealed class BackupSettings
{
    public bool DailyBackup { get; set; }
    public int IntervalHours { get; set; } = 24;
    public int RetentionDays { get; set; } = 7;
    public string BackupDirectory { get; set; } = string.Empty;
    public DateTimeOffset? LastBackupAt { get; set; }
}

public sealed class OrganizationSettings
{
    public bool Enabled { get; set; }
    public bool RunOnStartup { get; set; } = true;
    public bool RunOnDesktopChanges { get; set; }
    public bool ReassignExistingItems { get; set; }
}

public sealed class OrganizationRule
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string BuiltInId { get; set; } = string.Empty;
    public string Title { get; set; } = "新规则";
    public bool Enabled { get; set; } = true;
    public int Priority { get; set; }
    public List<DesktopItemKind> ItemKinds { get; set; } = [];
    public string NamePattern { get; set; } = "*";
    public List<string> Extensions { get; set; } = [];
    public OrganizationRuleAction Action { get; set; } = OrganizationRuleAction.AssignToBox;
    public Guid? TargetBoxId { get; set; }
}

public sealed class CrabDeskState
{
    public int SchemaVersion { get; set; } = 21;
    public AppSettings Settings { get; set; } = new();
    public List<DesktopBox> Boxes { get; set; } = [];
    public Dictionary<string, Guid> Assignments { get; set; } = new(StringComparer.OrdinalIgnoreCase);
    public Dictionary<string, DesktopIconPlacement> DesktopIconPositions { get; set; } = new(StringComparer.OrdinalIgnoreCase);
    public Dictionary<string, DesktopIconLayoutSnapshot> DesktopIconLayout { get; set; } = new(StringComparer.OrdinalIgnoreCase);
    public OrganizationSettings Organization { get; set; } = new();
    public List<OrganizationRule> OrganizationRules { get; set; } = [];

    [JsonIgnore]
    public bool MigratedFromLegacyIconTakeover { get; set; }

    [JsonIgnore]
    public DesktopBox? UnassignedBox => Boxes.FirstOrDefault(box => !box.IsSystemBox && !box.IsMappedFolder);

    [JsonIgnore]
    public DesktopBox? SystemBox => Boxes.FirstOrDefault(box => box.IsSystemBox);
}

public readonly record struct DesktopIconPositionSnapshot(string DisplayName, int X, int Y);
public readonly record struct DesktopWorkAreaSnapshot(int Left, int Top, int Right, int Bottom);
