using System.IO.Enumeration;

namespace CrabDesk.Core;

public sealed record OrganizationDecision(
    string ItemKey,
    string ItemName,
    Guid RuleId,
    string RuleTitle,
    OrganizationRuleAction Action,
    Guid? TargetBoxId);

public sealed record OrganizationApplyResult(
    int Assigned,
    int Unassigned,
    int Ignored,
    int InvalidTargets,
    IReadOnlyList<OrganizationDecision> Decisions);

public sealed record OrganizationRuleConflict(
    Guid FirstRuleId,
    string FirstRuleTitle,
    Guid SecondRuleId,
    string SecondRuleTitle);

public sealed class OrganizationRuleEngine : IOrganizationRuleEngine
{
    public IReadOnlyList<OrganizationDecision> Preview(
        CrabDeskState state,
        IReadOnlyList<DesktopItemRef> items,
        bool reassignExistingItems = false)
    {
        var rules = state.OrganizationRules
            .Select((rule, index) => (Rule: rule, Index: index))
            .Where(entry => entry.Rule.Enabled)
            .OrderBy(entry => entry.Rule.Priority)
            .ThenBy(entry => entry.Index)
            .Select(entry => entry.Rule)
            .ToArray();
        var decisions = new List<OrganizationDecision>();
        foreach (var item in items)
        {
            var key = item.Key.ToString();
            if (!reassignExistingItems && state.Assignments.ContainsKey(key))
            {
                continue;
            }

            var rule = rules.FirstOrDefault(candidate => MatchesRule(candidate, item));
            if (rule is null)
            {
                continue;
            }

            decisions.Add(new OrganizationDecision(
                key,
                item.DisplayName,
                rule.Id,
                rule.Title,
                rule.Action,
                rule.TargetBoxId));
        }
        return decisions;
    }

    // The box a rule writes into, or null when none exists yet and organizing
    // has to create one. An explicit target wins; when it is missing (the box
    // was deleted) or was never chosen, the rule adopts an existing normal box
    // with the same title. That title match deliberately covers every normal
    // box, not just the ones a previous organize run generated: a same-name box
    // the user created by hand or the AI classifier created was previously
    // ignored, and organizing added a duplicate next to it.
    public static DesktopBox? ResolveTargetBox(CrabDeskState state, OrganizationRule rule)
    {
        if (rule.TargetBoxId is { } target &&
            state.Boxes.FirstOrDefault(box => box.Id == target && !box.IsMappedFolder) is { } explicitTarget)
        {
            return explicitTarget;
        }

        var title = rule.Title.Trim();
        var matches = state.Boxes.Where(box =>
            !box.IsMappedFolder &&
            string.Equals(box.Title.Trim(), title, StringComparison.CurrentCultureIgnoreCase));
        // A box an earlier organize run generated is the one this rule already
        // owns and keeps titled, so prefer it and leave user boxes alone.
        return matches.FirstOrDefault(box => box.IsAutoGenerated) ?? matches.FirstOrDefault();
    }

    // Whether an organize pass may delete a box it found empty. Only boxes the
    // pass generated itself qualify: a box the user created by hand is never
    // removed, not even when a rule targets it and it currently holds nothing.
    //
    // "Empty" is judged against live items, not against the assignment table.
    // An assignment whose desktop item was deleted survives in state (nothing
    // prunes it on the ordinary organize path), so counting assignments alone
    // reported such a box as occupied and organize left a visibly empty box
    // sitting on the desktop.
    public static bool CanRemoveEmptyBox(
        CrabDeskState state,
        DesktopBox box,
        OrganizationRule rule,
        IReadOnlySet<string>? liveItemKeys = null)
    {
        if (!box.IsAutoGenerated ||
            state.Assignments.Any(pair =>
                pair.Value == box.Id && IsLive(pair.Key, liveItemKeys)))
        {
            return false;
        }

        return !state.OrganizationRules.Any(candidate =>
            candidate.Id != rule.Id &&
            candidate.Enabled &&
            candidate.Action == OrganizationRuleAction.AssignToBox &&
            candidate.TargetBoxId == box.Id);
    }

    // How many items a rule's box will hold once these decisions are applied:
    // the items the engine hands to the rule, plus those already sitting in
    // the box that no decision moves. Matching the rule against the desktop
    // on its own overstates this — a higher-priority rule may claim the item
    // first, or it may already live in another box and be skipped — and a
    // box created on that basis ends up empty.
    //
    // The items already in the box are filtered to live ones for the same
    // reason as in CanRemoveEmptyBox: a stale assignment would otherwise keep
    // an empty box alive or inflate the height it is sized to.
    public static int CountProjectedItems(
        IReadOnlyList<OrganizationDecision> decisions,
        IReadOnlyDictionary<string, Guid> assignments,
        Guid ruleId,
        Guid? boxId,
        IReadOnlySet<string>? liveItemKeys = null)
    {
        var incoming = 0;
        var decided = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var decision in decisions)
        {
            decided.Add(decision.ItemKey);
            if (decision.Action == OrganizationRuleAction.AssignToBox && decision.RuleId == ruleId)
            {
                incoming++;
            }
        }

        if (boxId is not { } box)
        {
            return incoming;
        }
        return incoming + assignments.Count(entry =>
            entry.Value == box &&
            !decided.Contains(entry.Key) &&
            IsLive(entry.Key, liveItemKeys));
    }

    // A null key set means the caller has no opinion (tests and callers that
    // already pass a pruned assignment table); anything present is live.
    private static bool IsLive(string itemKey, IReadOnlySet<string>? liveItemKeys) =>
        liveItemKeys is null || liveItemKeys.Contains(itemKey);

    public OrganizationApplyResult Apply(
        CrabDeskState state,
        IReadOnlyList<DesktopItemRef> items,
        bool reassignExistingItems = false)
    {
        var decisions = Preview(state, items, reassignExistingItems);
        // Mapped folders mirror a live directory; rules must not move items
        // into them. Keep this in sync with CrabDeskRuntime which also
        // excludes mapped boxes when it applies the same decisions.
        var validBoxes = state.Boxes.Where(box => !box.IsMappedFolder).Select(box => box.Id).ToHashSet();
        var assigned = 0;
        var unassigned = 0;
        var ignored = 0;
        var invalidTargets = 0;
        foreach (var decision in decisions)
        {
            switch (decision.Action)
            {
                case OrganizationRuleAction.AssignToBox:
                    if (decision.TargetBoxId is not { } target || !validBoxes.Contains(target))
                    {
                        invalidTargets++;
                        break;
                    }
                    state.Assignments[decision.ItemKey] = target;
                    assigned++;
                    break;
                case OrganizationRuleAction.KeepUnassigned:
                    if (reassignExistingItems && state.Assignments.Remove(decision.ItemKey))
                    {
                        unassigned++;
                    }
                    break;
                case OrganizationRuleAction.Ignore:
                    ignored++;
                    break;
            }
        }
        return new OrganizationApplyResult(assigned, unassigned, ignored, invalidTargets, decisions);
    }

    public IReadOnlyList<OrganizationRuleConflict> FindConflicts(CrabDeskState state)
    {
        var rules = state.OrganizationRules.Where(rule => rule.Enabled).ToArray();
        var conflicts = new List<OrganizationRuleConflict>();
        for (var first = 0; first < rules.Length; first++)
        {
            for (var second = first + 1; second < rules.Length; second++)
            {
                if ((BuiltInOrganizationRules.IsFallback(rules[first]) &&
                        rules[first].Priority > rules[second].Priority) ||
                    (BuiltInOrganizationRules.IsFallback(rules[second]) &&
                        rules[second].Priority > rules[first].Priority))
                {
                    continue;
                }
                if (!MayOverlap(rules[first], rules[second]))
                {
                    continue;
                }
                conflicts.Add(new OrganizationRuleConflict(
                    rules[first].Id,
                    rules[first].Title,
                    rules[second].Id,
                    rules[second].Title));
            }
        }
        return conflicts;
    }

    public static bool MatchesRule(OrganizationRule rule, DesktopItemRef item)
    {
        if (rule.ItemKinds.Count > 0 && !rule.ItemKinds.Contains(item.Kind))
        {
            return false;
        }

        if (!FileSystemName.MatchesSimpleExpression(
                string.IsNullOrWhiteSpace(rule.NamePattern) ? "*" : rule.NamePattern,
                item.DisplayName,
                true))
        {
            return false;
        }

        if (rule.Extensions.Count == 0)
        {
            return true;
        }

        var extension = Path.GetExtension(item.FileSystemPath ?? item.DisplayName);
        return rule.Extensions.Any(candidate => string.Equals(
            NormalizeExtension(candidate),
            NormalizeExtension(extension),
            StringComparison.OrdinalIgnoreCase));
    }

    private static bool MayOverlap(OrganizationRule first, OrganizationRule second)
    {
        var kindsOverlap = first.ItemKinds.Count == 0 || second.ItemKinds.Count == 0 ||
            first.ItemKinds.Intersect(second.ItemKinds).Any();
        if (!kindsOverlap)
        {
            return false;
        }

        var firstExtensions = first.Extensions.Select(NormalizeExtension).ToHashSet(StringComparer.OrdinalIgnoreCase);
        var secondExtensions = second.Extensions.Select(NormalizeExtension).ToHashSet(StringComparer.OrdinalIgnoreCase);
        var extensionsOverlap = firstExtensions.Count == 0 || secondExtensions.Count == 0 ||
            firstExtensions.Overlaps(secondExtensions);
        if (!extensionsOverlap)
        {
            return false;
        }

        var firstPattern = string.IsNullOrWhiteSpace(first.NamePattern) ? "*" : first.NamePattern.Trim();
        var secondPattern = string.IsNullOrWhiteSpace(second.NamePattern) ? "*" : second.NamePattern.Trim();
        return PatternsOverlap(firstPattern, secondPattern);
    }

    // Decides whether two file-system wildcard patterns can match a common
    // string. "*" and "?" follow FileSystemName.MatchesSimpleExpression
    // semantics; "[...]" classes are approximated as "any one character" so
    // the check stays conservative and never misses a real conflict.
    private static bool PatternsOverlap(string firstPattern, string secondPattern)
    {
        if (string.Equals(firstPattern, secondPattern, StringComparison.OrdinalIgnoreCase) ||
            firstPattern == "*" ||
            secondPattern == "*")
        {
            return true;
        }
        return GlobNfasIntersect(CompileGlob(firstPattern), CompileGlob(secondPattern));
    }

    private static IReadOnlyList<GlobSegment> CompileGlob(string pattern)
    {
        var segments = new List<GlobSegment>();
        for (var index = 0; index < pattern.Length; index++)
        {
            switch (pattern[index])
            {
                case '*':
                    segments.Add(new GlobSegment(GlobKind.Star, '\0'));
                    break;
                case '?':
                    segments.Add(new GlobSegment(GlobKind.Any, '\0'));
                    break;
                case '[':
                {
                    var close = pattern.IndexOf(']', index + 1);
                    if (close > index)
                    {
                        index = close;
                    }
                    segments.Add(new GlobSegment(GlobKind.Any, '\0'));
                    break;
                }
                default:
                    segments.Add(new GlobSegment(GlobKind.Literal, char.ToLowerInvariant(pattern[index])));
                    break;
            }
        }
        return segments;
    }

    // Product reachability search over the two pattern NFAs. A shared
    // accepting state means some string is matched by both patterns.
    private static bool GlobNfasIntersect(
        IReadOnlyList<GlobSegment> first,
        IReadOnlyList<GlobSegment> second)
    {
        var visited = new HashSet<(int, int)>();
        var queue = new Queue<(int, int)>();
        queue.Enqueue((0, 0));
        visited.Add((0, 0));
        while (queue.Count > 0)
        {
            var (firstIndex, secondIndex) = queue.Dequeue();
            if (firstIndex == first.Count && secondIndex == second.Count)
            {
                return true;
            }
            var left = firstIndex < first.Count ? first[firstIndex] : (GlobSegment?)null;
            var right = secondIndex < second.Count ? second[secondIndex] : (GlobSegment?)null;

            // A star may match the empty string, so it can be skipped.
            if (left is { Kind: GlobKind.Star })
            {
                TryVisit(queue, visited, (firstIndex + 1, secondIndex));
            }
            if (right is { Kind: GlobKind.Star })
            {
                TryVisit(queue, visited, (firstIndex, secondIndex + 1));
            }

            if (left is null || right is null)
            {
                continue;
            }

            // Consume one character. A star absorbs whatever the other side
            // needs; otherwise both segments must agree on the character.
            if (left.Value.Kind == GlobKind.Star && right.Value.Kind != GlobKind.Star)
            {
                TryVisit(queue, visited, (firstIndex, secondIndex + 1));
            }
            else if (right.Value.Kind == GlobKind.Star && left.Value.Kind != GlobKind.Star)
            {
                TryVisit(queue, visited, (firstIndex + 1, secondIndex));
            }
            else if (left.Value.Kind != GlobKind.Star &&
                     right.Value.Kind != GlobKind.Star &&
                     GlobSegmentsCanMatch(left.Value, right.Value))
            {
                TryVisit(queue, visited, (firstIndex + 1, secondIndex + 1));
            }
        }
        return false;
    }

    private static void TryVisit(
        Queue<(int, int)> queue,
        HashSet<(int, int)> visited,
        (int, int) state)
    {
        if (visited.Add(state))
        {
            queue.Enqueue(state);
        }
    }

    private static bool GlobSegmentsCanMatch(GlobSegment first, GlobSegment second)
    {
        if (first.Kind == GlobKind.Any || second.Kind == GlobKind.Any)
        {
            return true;
        }
        return first.Kind == GlobKind.Literal &&
            second.Kind == GlobKind.Literal &&
            first.Literal == second.Literal;
    }

    private enum GlobKind
    {
        Star,
        Any,
        Literal
    }

    private readonly record struct GlobSegment(GlobKind Kind, char Literal);

    private static string NormalizeExtension(string value)
    {
        var extension = value.Trim();
        if (extension.Length == 0)
        {
            return string.Empty;
        }
        return extension.StartsWith('.') ? extension.ToLowerInvariant() : "." + extension.ToLowerInvariant();
    }
}
