using System.Reflection;
using System.Runtime.CompilerServices;
using CrabDesk.Core;
using CrabDesk.Runtime;
using Xunit;

namespace CrabDesk.WinUI.Tests;

/// <summary>
/// A box can look occupied to the organizer while rendering nothing: the
/// assignments pointing at it may reference desktop items that no longer
/// exist. Those phantom assignments must not keep an otherwise empty
/// auto-generated box alive, or organizing leaves a visibly empty box behind.
/// </summary>
public sealed class OrganizationEmptyBoxTests
{
    [Fact]
    public void AnAutoGeneratedBoxHoldingOnlyMissingItemsIsRemoved()
    {
        var autoBox = new DesktopBox
        {
            Title = "文档",
            MonitorId = "primary",
            IsAutoGenerated = true,
            Bounds = new LayoutRect(40, 40, 360, 190)
        };
        var rule = new OrganizationRule
        {
            Id = Guid.NewGuid(),
            BuiltInId = BuiltInOrganizationRules.DocumentsId,
            Title = "文档",
            Extensions = [".docx"],
            Action = OrganizationRuleAction.AssignToBox,
            TargetBoxId = autoBox.Id
        };
        var state = new CrabDeskState
        {
            Boxes = [autoBox],
            OrganizationRules = [rule],
            // The file this assignment points at was deleted from the desktop.
            Assignments = { ["file:VOL:00000001"] = autoBox.Id }
        };
        var runtime = CreateRuntime(state, []);

        RunOrganizePass(runtime);

        Assert.Empty(state.Boxes);
    }

    [Fact]
    public void AnAutoGeneratedBoxHoldingALiveItemIsKept()
    {
        var autoBox = new DesktopBox
        {
            Title = "文档",
            MonitorId = "primary",
            IsAutoGenerated = true,
            Bounds = new LayoutRect(40, 40, 360, 190)
        };
        var rule = new OrganizationRule
        {
            Id = Guid.NewGuid(),
            BuiltInId = BuiltInOrganizationRules.DocumentsId,
            Title = "文档",
            Extensions = [".docx"],
            Action = OrganizationRuleAction.AssignToBox,
            TargetBoxId = autoBox.Id
        };
        var item = Item("keep.docx", DesktopItemKind.File);
        var state = new CrabDeskState
        {
            Boxes = [autoBox],
            OrganizationRules = [rule],
            Assignments = { [item.Key.ToString()] = autoBox.Id }
        };
        var runtime = CreateRuntime(state, [item]);

        RunOrganizePass(runtime);

        Assert.Same(autoBox, Assert.Single(state.Boxes));
    }

    [Fact]
    public void MissingItemsDoNotCreateABoxOnTheirOwn()
    {
        // No live item matches, yet a phantom assignment points at the rule's
        // title. Organizing must not resurrect a box for a file that is gone.
        var rule = new OrganizationRule
        {
            Id = Guid.NewGuid(),
            BuiltInId = BuiltInOrganizationRules.ImagesId,
            Title = "图片",
            Extensions = [".png"],
            Action = OrganizationRuleAction.AssignToBox
        };
        var ghostBox = new DesktopBox
        {
            Title = "其它",
            MonitorId = "primary",
            Bounds = new LayoutRect(500, 40, 360, 190)
        };
        var state = new CrabDeskState
        {
            Boxes = [ghostBox],
            OrganizationRules = [rule],
            Assignments = { ["file:VOL:00000002"] = ghostBox.Id }
        };
        var runtime = CreateRuntime(state, []);

        RunOrganizePass(runtime);

        // "图片" has nothing live to collect, so no box may be created for it.
        Assert.DoesNotContain(state.Boxes, box => box.Title == "图片");
    }

    [Fact]
    public void EveryBoxAnOrganizePassCreatesActuallyReceivesItsItems()
    {
        // The existing box-reuse tests only assert that a box exists and that
        // the rule points at it. That would still pass if the pass created a
        // box and then never assigned anything into it, which is exactly the
        // "organize created an empty box" report, so check the whole path:
        // create the structure, apply the decisions, then read the box back.
        var state = new CrabDeskState
        {
            OrganizationRules = BuiltInOrganizationRules.CreateDefaults()
        };
        var items = new[]
        {
            Item("notes.docx", DesktopItemKind.File),
            Item("photo.png", DesktopItemKind.File),
            Item("archive.zip", DesktopItemKind.File)
        };
        var runtime = CreateRuntime(state, items);

        var created = RunOrganizePass(runtime);
        Assert.NotEmpty(created);
        var assignedCount = ApplyDecisions(runtime);

        // Every box the pass created must end up holding at least one item.
        // A box that survives the pass with nothing in it is the reported bug.
        foreach (var boxId in created)
        {
            var box = state.Boxes.First(candidate => candidate.Id == boxId);
            var assigned = state.Assignments.Count(pair => pair.Value == boxId);
            Assert.True(
                assigned > 0,
                $"organize created box '{box.Title}' and assigned nothing into it");
        }

        Assert.Equal(items.Length, assignedCount);

        // And each item is reachable through the box it was assigned to.
        foreach (var item in items)
        {
            var boxId = state.Assignments[item.Key.ToString()];
            Assert.Contains(state.Boxes, box => box.Id == boxId);
        }
    }

    [Fact]
    public void RulesWithNothingToCollectDoNotGetABox()
    {
        // Only a .docx exists, so the images and archives rules must stay
        // without a box instead of adding empty ones beside the documents box.
        var state = new CrabDeskState
        {
            OrganizationRules = BuiltInOrganizationRules.CreateDefaults()
        };
        var runtime = CreateRuntime(state, [Item("notes.docx", DesktopItemKind.File)]);

        var created = RunOrganizePass(runtime);

        Assert.Single(created);
        var box = Assert.Single(state.Boxes);
        Assert.Equal("文档", box.Title);
        Assert.DoesNotContain(state.Boxes, candidate => candidate.Title == "图片");
        Assert.DoesNotContain(state.Boxes, candidate => candidate.Title == "压缩");
        Assert.DoesNotContain(state.Boxes, candidate => candidate.Title == "目录");
    }

    /// <summary>
    /// Runs the apply half directly, so the assertions read the real
    /// assignment table. The runtime's own ApplyOrganizationRules is not used
    /// because it ends in ScheduleSave, which needs timers the uninitialized
    /// test instance does not have.
    /// </summary>
    [Fact]
    public void ACustomRulesAutoBoxIsRemovedOnceItsItemsAreDeleted()
    {
        // The real sequence: a first pass creates the box for a matching file,
        // then the user deletes that file and organizes again. The box has
        // nothing left to collect, so it must not stay on the desktop.
        var rule = new OrganizationRule
        {
            Id = Guid.NewGuid(),
            Title = "工作",
            Extensions = [".psd"],
            Action = OrganizationRuleAction.AssignToBox
        };
        var state = new CrabDeskState
        {
            OrganizationRules = [rule]
        };
        var runtime = CreateRuntime(state, [Item("mockup.psd", DesktopItemKind.File)]);

        RunOrganizePass(runtime);
        var box = Assert.Single(state.Boxes);
        Assert.Equal("工作", box.Title);
        Assert.Equal(box.Id, rule.TargetBoxId);

        // The file is deleted from the desktop.
        SetItems(runtime, []);
        RunOrganizePass(runtime);

        Assert.DoesNotContain(state.Boxes, candidate => candidate.Title == "工作");
        Assert.Null(rule.TargetBoxId);
    }

    [Fact]
    public void ABuiltInRulesAutoBoxIsRemovedOnceItsItemsAreDeleted()
    {
        var state = new CrabDeskState
        {
            OrganizationRules = BuiltInOrganizationRules.CreateDefaults()
        };
        var runtime = CreateRuntime(state, [Item("photo.png", DesktopItemKind.File)]);

        RunOrganizePass(runtime);
        var box = Assert.Single(state.Boxes);
        Assert.Equal("图片", box.Title);

        SetItems(runtime, []);
        RunOrganizePass(runtime);

        Assert.Empty(state.Boxes);
    }

    [Fact]
    public void AUsersOwnBoxIsNeverRemovedEvenWhenItIsEmpty()
    {
        // Only auto-generated boxes are organize's to clean up.
        var userBox = new DesktopBox
        {
            Title = "工作",
            MonitorId = "primary",
            Bounds = new LayoutRect(40, 40, 360, 190)
        };
        var rule = new OrganizationRule
        {
            Id = Guid.NewGuid(),
            Title = "工作",
            Extensions = [".psd"],
            Action = OrganizationRuleAction.AssignToBox,
            TargetBoxId = userBox.Id
        };
        var state = new CrabDeskState
        {
            Boxes = [userBox],
            OrganizationRules = [rule]
        };
        var runtime = CreateRuntime(state, []);

        RunOrganizePass(runtime);

        Assert.Same(userBox, Assert.Single(state.Boxes));
    }

    private static void SetItems(CrabDeskRuntime runtime, IReadOnlyList<DesktopItemRef> items) =>
        Set(runtime, "<Items>k__BackingField", items);

    private static int ApplyDecisions(CrabDeskRuntime runtime)
    {
        var state = (CrabDeskState)typeof(CrabDeskRuntime)
            .GetProperty("State", BindingFlags.Instance | BindingFlags.Public)!
            .GetValue(runtime)!;
        var items = (IReadOnlyList<DesktopItemRef>)typeof(CrabDeskRuntime)
            .GetProperty("Items", BindingFlags.Instance | BindingFlags.Public)!
            .GetValue(runtime)!;
        var engine = new OrganizationRuleEngine();
        var result = engine.Apply(state, items, state.Organization.ReassignExistingItems);
        return result.Assigned;
    }

    private static CrabDeskRuntime CreateRuntime(CrabDeskState state, IReadOnlyList<DesktopItemRef> items)
    {
        var runtime = (CrabDeskRuntime)RuntimeHelpers.GetUninitializedObject(typeof(CrabDeskRuntime));
        var monitor = new MonitorLayout
        {
            Id = "primary",
            DeviceName = "primary",
            IsPrimary = true,
            DpiScale = 1,
            Bounds = new LayoutRect(0, 0, 1920, 1080),
            WorkArea = new LayoutRect(0, 0, 1920, 1040),
            PixelBounds = new LayoutRect(0, 0, 1920, 1080),
            PixelWorkArea = new LayoutRect(0, 0, 1920, 1040)
        };
        Set(runtime, "<State>k__BackingField", state);
        Set(runtime, "<Items>k__BackingField", items);
        Set(runtime, "<Monitors>k__BackingField", new[] { monitor });
        Set(runtime, "_organizationRuleEngine", new OrganizationRuleEngine());
        return runtime;
    }

    private static HashSet<Guid> RunOrganizePass(CrabDeskRuntime runtime)
    {
        var method = typeof(CrabDeskRuntime).GetMethod(
            "EnsureSmartOrganizationStructure",
            BindingFlags.Instance | BindingFlags.NonPublic)!;
        return (HashSet<Guid>)method.Invoke(runtime, null)!;
    }

    private static void Set(object instance, string name, object value) =>
        instance.GetType().GetField(name, BindingFlags.Instance | BindingFlags.NonPublic)!
            .SetValue(instance, value);

    private static DesktopItemRef Item(string name, DesktopItemKind kind) => new()
    {
        Key = new DesktopItemKey("file", name),
        DisplayName = name,
        ParsingName = name,
        FileSystemPath = Path.Combine("C:\\Desktop", name),
        Kind = kind
    };
}
