using Xunit;

using CrabDesk.Core;
using CrabDesk.Runtime;

namespace CrabDesk.WinUI.Tests;

public sealed class OrganizationStructureTests
{
    [Fact]
    public void OrganizationKeepsExistingAutoBoxPositionsAndPlacesNewBoxesElsewhere()
    {
        var existing = new DesktopBox
        {
            Title = "文档",
            MonitorId = "primary",
            IsAutoGenerated = true,
            Bounds = new LayoutRect(300, 420, 360, 190)
        };
        var fresh = new DesktopBox
        {
            Title = "图片",
            MonitorId = "primary",
            IsAutoGenerated = true
        };
        var active = new List<(DesktopBox Box, int ItemCount)>
        {
            (existing, 2),
            (fresh, 5)
        };
        var createdBoxIds = new HashSet<Guid> { fresh.Id };

        CrabDeskRuntime.PlaceAutoGeneratedBoxes(
            active,
            createdBoxIds,
            "primary",
            new LayoutRect(0, 0, 1920, 1040),
            []);

        Assert.Equal(new LayoutRect(300, 420, 360, 190), existing.Bounds);
        Assert.Equal("primary", existing.MonitorId);
        Assert.True(fresh.Bounds.Width > 0);
        Assert.True(fresh.Bounds.Height > 0);
        Assert.False(existing.Bounds.Intersects(fresh.Bounds));
    }
}