using System.Reflection;
using System.Runtime.CompilerServices;
using CrabDesk.Core;
using CrabDesk.Runtime;
using Xunit;

namespace CrabDesk.WinUI.Tests;

/// <summary>
/// Pins the box-reuse contract of an organize pass. A rule whose title already
/// matches an existing normal box must write into that box instead of adding a
/// second one beside it, and an organize pass must never delete a box the user
/// created by hand.
/// </summary>
public sealed class OrganizationBoxReuseTests
{
    [Fact]
    public void OrganizeReusesAnExistingSameNameBoxInsteadOfCreatingADuplicate()
    {
        // "图片" already exists as an ordinary box — created by the AI
        // classifier or by hand, so IsAutoGenerated is false.
        var existing = new DesktopBox
        {
            Title = "图片",
            MonitorId = "primary",
            Bounds = new LayoutRect(40, 40, 360, 190)
        };
        var rule = new OrganizationRule
        {
            Id = Guid.NewGuid(),
            Title = "图片",
            Extensions = ["png"],
            Action = OrganizationRuleAction.AssignToBox
        };
        var state = new CrabDeskState
        {
            Boxes = [existing],
            OrganizationRules = [rule]
        };
        var runtime = CreateRuntime(state, [Item("photo.png", DesktopItemKind.File)]);

        var created = RunOrganizePass(runtime);

        var box = Assert.Single(state.Boxes);
        Assert.Same(existing, box);
        Assert.Empty(created);
        Assert.Equal(existing.Id, rule.TargetBoxId);
    }

    [Fact]
    public void OrganizeReusesASameNameBoxItGeneratedOnAnEarlierRun()
    {
        var generated = new DesktopBox
        {
            Title = "图片",
            MonitorId = "primary",
            IsAutoGenerated = true,
            Bounds = new LayoutRect(40, 40, 360, 190)
        };
        var rule = new OrganizationRule
        {
            Id = Guid.NewGuid(),
            Title = "图片",
            Extensions = ["png"],
            Action = OrganizationRuleAction.AssignToBox,
            TargetBoxId = generated.Id
        };
        var state = new CrabDeskState
        {
            Boxes = [generated],
            OrganizationRules = [rule]
        };
        var runtime = CreateRuntime(state, [Item("photo.png", DesktopItemKind.File)]);

        RunOrganizePass(runtime);

        Assert.Same(generated, Assert.Single(state.Boxes));
        Assert.Equal(generated.Id, rule.TargetBoxId);
    }

    [Fact]
    public void OrganizeKeepsAnEmptyBoxTheUserCreatedByHand()
    {
        var userBox = new DesktopBox
        {
            Title = "资料",
            MonitorId = "primary",
            Bounds = new LayoutRect(40, 40, 360, 190)
        };
        var rule = new OrganizationRule
        {
            Id = Guid.NewGuid(),
            Title = "资料",
            Extensions = ["txt"],
            Action = OrganizationRuleAction.AssignToBox,
            TargetBoxId = userBox.Id
        };
        var state = new CrabDeskState
        {
            Boxes = [userBox],
            OrganizationRules = [rule]
        };
        // Nothing on the desktop matches the rule, so it projects zero items.
        var runtime = CreateRuntime(state, []);

        RunOrganizePass(runtime);

        Assert.Same(userBox, Assert.Single(state.Boxes));
    }

    [Fact]
    public void OrganizeCreatesExactlyOneBoxPerDistinctRuleTitle()
    {
        var state = new CrabDeskState
        {
            OrganizationRules =
            [
                new OrganizationRule
                {
                    Id = Guid.NewGuid(),
                    Title = "图片",
                    Priority = 10,
                    Extensions = ["png"],
                    Action = OrganizationRuleAction.AssignToBox
                },
                new OrganizationRule
                {
                    Id = Guid.NewGuid(),
                    Title = "图片",
                    Priority = 20,
                    Extensions = ["jpg"],
                    Action = OrganizationRuleAction.AssignToBox
                }
            ]
        };
        var runtime = CreateRuntime(
            state,
            [Item("photo.png", DesktopItemKind.File), Item("scan.jpg", DesktopItemKind.File)]);

        RunOrganizePass(runtime);

        var box = Assert.Single(state.Boxes);
        Assert.Equal("图片", box.Title);
        Assert.All(state.OrganizationRules, rule => Assert.Equal(box.Id, rule.TargetBoxId));
    }

    private static CrabDeskRuntime CreateRuntime(CrabDeskState state, IReadOnlyList<DesktopItemRef> items)
    {
        var runtime = (CrabDeskRuntime)RuntimeHelpers.GetUninitializedObject(typeof(CrabDeskRuntime));
        var monitor = new MonitorLayout
        {
            Id = "primary",
            DeviceName = "primary",
            IsPrimary = true,
            DpiScale = 1,
            Bounds = new LayoutRect(0, 0, 1920, 1080),
            WorkArea = new LayoutRect(0, 0, 1920, 1040),
            PixelBounds = new LayoutRect(0, 0, 1920, 1080),
            PixelWorkArea = new LayoutRect(0, 0, 1920, 1040)
        };
        Set(runtime, "<State>k__BackingField", state);
        Set(runtime, "<Items>k__BackingField", items);
        Set(runtime, "<Monitors>k__BackingField", new[] { monitor });
        // Field initializers never run on an uninitialized instance.
        Set(runtime, "_organizationRuleEngine", new OrganizationRuleEngine());
        return runtime;
    }

    /// <summary>Invokes the organize pass and returns the ids of the boxes it created.</summary>
    private static HashSet<Guid> RunOrganizePass(CrabDeskRuntime runtime)
    {
        var method = typeof(CrabDeskRuntime).GetMethod(
            "EnsureSmartOrganizationStructure",
            BindingFlags.Instance | BindingFlags.NonPublic)!;
        return (HashSet<Guid>)method.Invoke(runtime, null)!;
    }

    private static void Set(object instance, string name, object value) =>
        instance.GetType().GetField(name, BindingFlags.Instance | BindingFlags.NonPublic)!
            .SetValue(instance, value);

    private static DesktopItemRef Item(string name, DesktopItemKind kind) => new()
    {
        Key = new DesktopItemKey("test", name),
        DisplayName = name,
        ParsingName = name,
        FileSystemPath = Path.Combine("C:\\Desktop", name),
        Kind = kind
    };
}
